spring:
  data:
    mongodb:
      username: kariuki
      password: kariuki
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin
  kafka:
    consumer:
      group-id: paymentGroup,orderGroup
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.kariuki.ecommerce.kafka.order.OrderConfirmation,paymentConfirmation:com.kariuki.ecommerce.kafka.payment.PaymentConfirmation
  mail:
    host: localhost
    port: 1025
    username: kariuki
    password: kariuki
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8040